ALTER TABLE `ast_Taluka_M` ADD CONSTRAINT `XNOTIGWF71BMQFBYIOW5UQ` FOREIGN KEY (`countryId`) REFERENCES `ast_Country_M`(`countryId`);
ALTER TABLE `ast_Taluka_M` ADD CONSTRAINT `YMHT3R2FN5LRIBGZJSSA` FOREIGN KEY (`stateId`) REFERENCES `ast_State_M`(`stateId`);
ALTER TABLE `ast_Taluka_M` ADD CONSTRAINT `H1RO2WRGL0ZCFDQHOCLABG` FOREIGN KEY (`regionId`) REFERENCES `ast_Region_M`(`regionId`);
ALTER TABLE `ast_Taluka_M` ADD CONSTRAINT `6WZV0G3FQ38YBPAI7LGADG` FOREIGN KEY (`districtId`) REFERENCES `ast_District_M`(`districtId`);
