ALTER TABLE `ast_Login_T` ADD CONSTRAINT `3KMAR68XOWSSL1R15YNW7W` FOREIGN KEY (`userId`) REFERENCES `ast_User_T`(`userId`);
ALTER TABLE `ast_Login_T` ADD CONSTRAINT `YEI55X3AE3AQZU1QCSR1QW` FOREIGN KEY (`contactId`) REFERENCES `ast_CoreContacts_T`(`contactId`);
