ALTER TABLE `ast_RoleMenuBridge_TP` ADD CONSTRAINT `K5ANAMJDSWGUPNHXCGZ6OW` FOREIGN KEY (`roleId`) REFERENCES `ast_Roles_T`(`roleId`);
ALTER TABLE `ast_RoleMenuBridge_TP` ADD CONSTRAINT `VZM3APRGLAZERAIWPVZWA` FOREIGN KEY (`menuId`) REFERENCES `ast_AppMenus_M`(`menuId`);
