ALTER TABLE `ast_City_M` ADD CONSTRAINT `BFPLS8YGXAF0EYJXOKP5LQ` FOREIGN KEY (`countryId`) REFERENCES `ast_Country_M`(`countryId`);
ALTER TABLE `ast_City_M` ADD CONSTRAINT `2N74WHVO62UUDBVNJ4IGCW` FOREIGN KEY (`stateId`) REFERENCES `ast_State_M`(`stateId`);
