ALTER TABLE `ast_UserRoleBridge_T` ADD CONSTRAINT `VDJZTFCVZAN9DG6L3CW` FOREIGN KEY (`roleId`) REFERENCES `ast_Roles_T`(`roleId`);
ALTER TABLE `ast_UserRoleBridge_T` ADD CONSTRAINT `GGC7QGFQRL1BFJJJZIKXCQ` FOREIGN KEY (`userId`) REFERENCES `ast_User_T`(`userId`);
