ALTER TABLE `ast_District_M` ADD CONSTRAINT `TQWX8S641MJBYPVX7S2R4G` FOREIGN KEY (`countryId`) REFERENCES `ast_Country_M`(`countryId`);
ALTER TABLE `ast_District_M` ADD CONSTRAINT `EZDVIJDJ0KD5DRFA4VUHVA` FOREIGN KEY (`stateId`) REFERENCES `ast_State_M`(`stateId`);
ALTER TABLE `ast_District_M` ADD CONSTRAINT `H9ZNAE2FJL2CT1VBQQTRFG` FOREIGN KEY (`regionId`) REFERENCES `ast_Region_M`(`regionId`);
